### ISSUE TITLE
GFAstats error

### ISSUE THREAD

**Issue by aabaricalla** [Gabaldonlab/redundans#100]
Hola @Dfupa 
estoy usando la version de singularity de Redundans y me da error al momento de crear el GFA a partir del fasta.

```
Traceback (most recent call last):
  File "/root/src/redundans/redundans.py", line 727, in <module>
    main()
  File "/root/src/redundans/redundans.py", line 718, in main
    redundans(o.fastq, o.longreads, o.fasta, o.reference, o.outdir, o.mapq, \
  File "/root/src/redundans/redundans.py", line 361, in redundans
    generate_gfa_file(lastOutFn, threads)
  File "/root/src/redundans/redundans.py", line 114, in generate_gfa_file
    with open(abs_path_gfa, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/.gfas/genome/redundans/scaffolds.gfa'
```
siendo "genome/redundans" la carpeta de salida del pipeline. No veo una carpeta ".gfa".

Me pasó al crear "contigs.reduced.gfa" en sus primeros pasos, lo hice manualmente y continué el pipeline mediante "--resume", luego  me volvió a pasar luego de las iteraciones de SSpace. 

Espero sirva a otros.
Saludos.

**Comment by Dfupa** [comment]
Saludos @aabaricalla,

_Si no te parece mal, continuamos la conversación en inglés para el resto de la comunidad, dado que puede ser de interés general._

I've tried to reproduce the issue by relaunching redundans both in my **local** environment as well as my **docker** and **singularity** images and I was not able to do so. As this issue was specifically found on singularity, Ill provide a bit more information regarding my tests on it.

After setting up my redundans singularity image, I ran the example commands to test it resuming the same steps you mentioned, i.e.:

`singularity exec redundans.sif bash -c "/root/src/redundans/redundans.py -v -i /root/src/redundans/test/*_?.fq.gz -f /root/src/redundans/test/contigs.fa -o /tmp/run1 --resume"`

There were no errors reported and the .**gfa files were generated correctly**: 

```
Singularity> tail -n 2  /tmp/run1/contigs.reduced.gfa

P	NODE_84_length_296_cov_37.2407_ID_167	NODE_84_length_296_cov_37.2407_ID_167.1+	*
P	NODE_91_length_243_cov_37.1489_ID_181	NODE_91_length_243_cov_37.1489_ID_181.1+	*
```


I need more information in order to find where the issue lies ( a more complete log, the command used...). In the meantime I've decided to upload the **redundans.sif singularity image** I used to [https://cloud.sylabs.io/]( https://cloud.sylabs.io/.) 

`singularity pull library://cgenomics/redundans/redundans`

Please let me know if your issue persists after using the .sif image I provided and feel free to share the logs or commands used so I can try to fix the issue.

Cheers,

**Comment by aabaricalla** [comment]
Hi @Dfupa , I think I found the problem with gfa file generation.
I'm working with _Oncopeltus fasciatus_ and the folder that I'm using is "/home/data/ofas/...", which caused an incorrect replacement to the path from "/home/data/**ofas**/.." to "/home/data/**.gfas**/.."  crashing the next steps and aborting the proccess.
Now it's running flawlessly!

**Comment by Dfupa** [comment]
Hi @aabaricalla,

Glad to see you found and solved the problem!

**Comment by pwkooij** [comment]
I had a similar issue with a standard redundant run using long reads

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/pepijn/Documents/genomics/Ac200942.gfastq/redundans/asm5/contigs.reduced.gfa'
```

notice the folder name `Ac200942.gfastq`, which in fact should be `Ac200942/fastq`
It seems that somewhere in the script it changes the / for .g when it sees fa somewhere

**Comment by Ofsm** [comment]
Hi guys! I'm having same issue with the /fa/ replaced by .gfa/
FileNotFoundError: [Errno 2] No such file or directory: '/my_working/DIR/New_Data.gfastp_out/Pop/Fam_ID/2_AssemOUT/3_RedundansOUT/sp1/contigs.reduced.gfa'

My actual working directory is something like this:
/my_working/DIR/New_Data/fastp_out/Pop/Fam_ID/2_AssemOUT/3_RedundansOUT/sp1/

OS: Ubuntu 22.04.05, conda package 'redundans'

Command used:
redundans.py -v -f sp1.fa -o $outdir/ -t 10 --log log_redundans.txt --noscaffolding --nogapclosing --identity 0.7

I guess that the only solution is to avoid the use of any "fa" in your folder name?

Cheers

**Comment by aabaricalla** [comment]
> I guess that the only solution is to avoid the use of any "fa" in your folder name?

As you said @Ofsm, the [line 112 in "redundans.py"](https://github.com/Gabaldonlab/redundans/blob/master/redundans.py#L112) main file replace "fa" with "gfa" in all the path instead of the file extension, causing a break.
