### ISSUE TITLE
fasta2homozygous.py make my contig file empty

### ISSUE THREAD

**Issue by HouYan20** [Gabaldonlab/redundans#106]
Hi,

I have a genome fasta file after a HiFi assembly. I would like to run redundans but only the reducing option (no scaffolding and no gapclosing). I run the following command in **path ~/software/redundans/bin**, and then I got an empty contigs.fa, an empty contigs.fa.fai, and an empty contigs.fa.homozygous.fa.gz file. 

./fasta2homozygous.py -i contigs.fa -t 4

The log:
Homozygous assembly/ies will be written with input name + '.homozygous.fa.gz'
#file name	genome size	contigs	heterozygous size	[%]	heterozygous contigs	[%]	identity [%]	possible joins	homozygous size	[%]	homozygous contigs	[%]
I/O error(None): None
#Time elapsed: 0:00:00.028639

Does anyone know where the problem is?

**Comment by Dfupa** [comment]
Hi @HouYan20,

To be completely honest, I didn't completely check that ` fasta2homozygous.py `script functionality on its own was bug free, as I tend to use it as a python module for the main pipeline of redundans. While I can have a look at it, I would recommend you to run redundans with the options that ignore the short read scaffolding and gapclosing instead of running directly ` fasta2homozygous.py ` as redundans can accept as input a contig file without the illumina reads library.

Try running:

` ~/software/redundans/redundans.py -v --noscaffolding --nogapclosing -o ./results -f contigs.fa -m 4` 

Also consider whether using LASTal or minimap2 for the reduction using `--minimap2reduce` depending on your assembly complexity and whether you want to boost performance or sensitivity. Let me know if everything went ok!

**Comment by Dfupa** [comment]
Hi @HouYan20 ,

I finally got a look at it and fixed. If you want to use it as standalone, please pull this new commit. Although the above solution would have done the trick, I've decided to rescue `fasta2homozygous.py` functionality as standalone script. 

I'll close this issue for now, but feel free to comment if you happen to find any additional issue
