### ISSUE TITLE
Remove hardcoded path for SSPACE

### ISSUE THREAD

**Issue by eburgueno** [Gabaldonlab/redundans#15]
In https://github.com/lpryszcz/redundans/blob/master/redundans.py#L370 the assumption is that SSPACE will be installed under `~/src/SSPACE`. This is the case when using the automated installed, but not when the user installs the dependencies manually.

While `--spacebin` can be used at invoke time, it would be better to treat SSPACE the same way other dependencies are treated. I.e.: if it's not in the PATH warn the user and exit.

**Comment by lpryszcz** [comment]
This is not going to change, simply because in many systems (including mine) the [getopt.pl is missing](https://github.com/lpryszcz/redundans/tree/master/docs#sspace-fails-with-an-error-cant-locate-getoptspl-in-inc). 
It can be [installed system-wide with root priviledges](https://github.com/lpryszcz/redundans/tree/master/docs#sspace-fails-with-an-error-cant-locate-getoptspl-in-inc) or [provided as file in SSPACE PATH](https://github.com/lpryszcz/redundans#manual-installation) (this is what is done by INSTALL.sh), but then the SSPACE has to be executed with full path. 

Still, you can alter ./redundans.py and point SSPACEBIN to any path you wish by default.
