### ISSUE TITLE
How is scaffolds.reduced.fa created?

### ISSUE THREAD

**Issue by okokookk** [Gabaldonlab/redundans#48]
I ran redundans.py using the options --noscaffolding and --nogapclosing.
Below is the full run command I used.

python redundans.py --noscaffolding --nogapclosing -t 64 -f draft.contig.fa --identity 0.90 --overlap 0.95 --log draft.contig.log -o draft.contig

I used --noscaffolding, but not only contigs.reduced.fa, but scaffolds.reduced.fa was also written as output.
I did not use paired-end reads as input. What is the criteria that scaffolds.reduced.fa is output?
What is the difference between contigs.reduced.fa and scaffolds.reduced.fa?

**Comment by lpryszcz** [comment]
Hi, `scaffolds.reduced.fa` is the product of reduction of second to last step of the pipeline. Normally it's scaffolded and gap closed assembly (`scaffolds.filled.fa`), but in your case it's reduced contigs contigs.reduced.fa, since you run `--noscaffolding --nogapclosing`. Note, it's created even if there was no scaffolding. 

> What is the difference between contigs.reduced.fa and scaffolds.reduced.fa?

Simply scaffolds.reduced.fa in your case is result of two iteration of reduction.
