### ISSUE TITLE
Scaffolding without Illumina reads

### ISSUE THREAD

**Issue by ATVincent** [Gabaldonlab/redundans#49]
Hello,

First, I want to thank you for this remarkable tool.

I used Redundans with only PacBio reads since I do not have Illumina reads. Here is the command:

../redundans/redundans/redundans.py -v -t 6 --log LOG.redundans -l Reads_?.fastq -f contigs.fasta -o redundans_results

I was surprised to realize that Redundans can generate scaffolds without having pairing information provided by Illumina reads. Can I have some explications ? How it can determines the number of "N" ?

Thank you

**Comment by lpryszcz** [comment]
Hi, thanks for the nice words!
Redundans uses [pyScaf](https://github.com/lpryszcz/pyScaf) for long-read & reference based scaffolding. Since you have only long reads, you can try [DBG2OLC](https://github.com/yechengxi/DBG2OLC). It worked quite well for me on some data (better than pyScaf;) ). 
Let me know how it worked!
