### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by JonEilers** [Gabaldonlab/redundans#88]
Was running redundans with contigs from a platanus-allee assembly, a reference genome of the same species, and some pacbio long reads. I am getting this error: [error log](https://github.com/JonEilers/error_logs/blob/main/redundans.log)

command used
```bash
./redundans.py \
  -f /home/jon/Working_Files/japonicus_genome_project/platanus-allee/Platanus_allee_v2.2.2_Linux_x86_64/ajap_step10_contig.fa \
  -l /home/jon/Working_Files/sea_cuke_species_data/apostichopus_japonicus/apostichopus_japonicus_raw_genome_seq_data/SRR6282347.fasta \
  -t 70 \
  --reference /home/jon/Working_Files/genome_assemblies/japonicus/Ajap_genome.fasta \
  --log ajap-ajap_redun_plat-allee.txt \
  -o ajap-ajap_redun_plat-allee
```

Thoughts?

**Comment by Dfupa** [comment]
Hi Jon,

Sorry for the late reply. It seems that the error "maximum recursion depth exceeded" is due to the function _populate_scaffolds. The default recursion limit is set to 1000 in Python. To my knowledge Python does not optimize tail recursion and unbridled recursion causes stack overflows. 

If I were to guess, a fairly repetitive genome will struggle with the current implementation of the function, as it was indeed written as a recursive one. 

We've been working on the next big Redundans update, and we've also had a look at this function. In next release's beta version, we've rewritten it as a iterative process, but I am still not 100% happy with the performance. I would recommend skipping the long read scaffolding and stick with the reference based scaffolding with the reference genome of the species. Incidentally, if you really want to use long read scaffolding, you can do a dirty assembly from the pacbio reads (with Miniasm for example) and then use reference base scaffolding using as the reference the long reads-based assembly. 

I'll close this issue for now as we are currently having a look at it
