### ISSUE TITLE
Problem on performance 

### ISSUE THREAD

**Issue by Hai1983** [Gabaldonlab/redundans#89]
Hi 
I am use redundans with : 

"module load Python/2.7.16-GCCcore-8.3.0
/home/ulg/bbasv/daomhai/software/redundans/./redundans.py -v -i 350-R1.paired.fastq.gz 350-R2.paired.fastq.gz -f Catfish.asm.bp.p_ctg.fa -o Result"

And it not work with the confirm ;

" Options: Namespace(fasta='Catfish.asm.bp.p_ctg.fa', fastq=['350-R1.paired.fastq.gz', '350-R2.paired.fastq.gz'], identity=0.51, iters=2, joins=5, limit=0.2, linkratio=0.7, log=<open file '<stderr>', mode 'w' at 0x14e4b1dca1e0>, longreads=[], mapq=10, mem=16, minLength=200, nocleaning=True, nogapclosing=True, norearrangements=False, noreduction=True, noscaffolding=True, outdir='Result', overlap=0.8, reference='', resume=False, threads=4, tmp='/tmp', usebwa=False, verbose=True)
Directory Result exists!" 

May help to explain what is my problem ??
Thanks in advances!
Hai

**Comment by Dfupa** [comment]
Hi Hai,

So far what I can gather about your issue is that the output directory `Result` already exists. In order to avoid accidental loss of data, Redundans checks whether the output directory already exists and if so, stops the execution. 

Hope it has clarified your issue a bit. I'll close it for now, but let as know if you experience any other problem.
