### ISSUE TITLE
[ERROR] Empty FastA file encountered:

### ISSUE THREAD

**Issue by mgarl-10** [Gabaldonlab/redundans#91]
Hello,

I am trying to run redundans software using paired ends, long reads and a draft assembly but I keep getting this error:

[ERROR] Empty FastA file encountered: 

Do you know what could be the problem? The file is not empty. This is my script:

redundans.py -i ./illumina/Lib1_R1_001.fastq.gz ./illumina/Lib1_R2_001.fastq.gz  -l ccs_merged_runs.fastq -f ./hifiasm_assembly/hifiasm_assembly.fasta -o assembly_redundans

Thank you

**Comment by Dfupa** [comment]
Hi mgarl,

I am sorry for the late reply. It appears to be an issue with the fasta/fastq parsing for your Illumina library. Without a complete log, I am unable to figure out which was the problem exactly. Can you provide redundans raw fastq files instead of the compressed ones? 

It that doesn't work, can you share the error log?

**Comment by Dfupa** [comment]
This issue is marked as stale by the stale_bot.
